### ISSUE TITLE
Markdown CSS for UL LI P doesn't show markers

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2612]
For 
```
- text
- text
- text
```
Work fine
- text
- text
- text

But when 

For 
```
- text

- text

- text
```

transform to 

```html
<ul>
<li><p>text</p></li>
<li><p>text</p></li>
<li><p>text</p></li>
</ul>
```
with css
```css
.wall-entry .content p, .wall-entry .content a {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**That why `p.overflow` overlaps markers of UL**

P.S. See post https://community.humhub.com/content/perma?id=108939
