### ISSUE TITLE
.input-sm can not be user

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2682]
By default in HumHub
```css
.form-control {
    border: 2px solid #ededed;
    box-shadow: none;
    min-height: 35px;  /** cause */
}
```

.input-sm

```css
.input-sm {
    height: 30px;
    padding: 5px 10px;
    font-size: 12px;
    line-height: 1.5;
    border-radius: 3px;
}
```

Can be resolved without recreate css on local?
