### ISSUE TITLE
Add panel-info

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4803]
### Is your feature request related to a problem? Please describe.
As the issue title suggests, I already see that it's possible to use `panel-success`, `panel-warning`, `panel-danger` and `panel-default`

### Describe the solution you'd like
Add the following to the theme.css file
```css
.panel-info{
    border:2px solid #5bc0de
}
.panel-info .panel-heading{
    color:#5bc0de
}
````
### Describe alternatives you've considered
I've considered adding via custom theme but overall thought it a better solution to add to the core theme.css as it's missing there
