### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#654]
The issues still stand, most "questions" regarding HumHub are how to theme it. 

You should follow standard procedure with _.less files. Which is inherently *only_ for the developers of the system. Just like you mentioned, these files will be edited and updated with new versions of HumHub, thus the themes should **_not be based on *.less files**_ but based on **_overwriting files**_ which are not part of the update process.

That way you can update/change the base  CSS without interfering with themes. And it's up to the user to adjust class names or properties they are overwriting. 

I suggest all theme.less code be moved to a **_main.less**_ and provide **_ONLY**_ a 'theme.css' with the HumHub theme which only simply overwrites to the main systems CSS files. **It also should be inlcuded after ALL css** is loaded to be able to overwrite atwho, and other styles that are unthemeable without overwriting base files. For example:

**/themes/HumHub/css/theme.css**

``` css
/* Here you can overwrite CSS Classes from main.css 
 * Do not edit the core CSS files, this file is intended to overwrite any properties you want to change
 */

/* Example of overwriting base text color */
body {
    color: #777;
}

```

**_One file to rule them all**_ and in the darkness **bind them**
