### ISSUE TITLE
Issue with modal boxes when positioning an element at the bottom of the screen

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6889]
@luke- do we still need this?

```less
@media @responsive {
    .modal-open #layout-content {
        > .container {
            overflow-x: unset; // This fixes broken (invisible) richtext editor nav in ios safari...
        }
    }
}
```
https://github.com/humhub/humhub/blob/master/static/less/mobile.less#L26

Or can I replace it with `overflow-x: hidden;`?

Or was it for old iOs Safari?

It was added 5 years ago: Commit: https://github.com/humhub/humhub/commit/16201716f36ccc23b32725f3218c7f7a9982feec
Because if this issue: https://github.com/humhub/humhub/issues/3711

I don't understand why the fix is on `.modal-open` as the issue doesn't seam to be for modal boxes.

`overflow-x: unset;` creates a problem with the Clean Theme bottom menu: https://github.com/cuzy-app/humhub-modules-clean-theme/issues/13#issuecomment-2001897924

And the only way to fix it is to replace `overflow-x: unset;` with any other `overflow-x` value. `hidden` could be fine.
Thanks!
