### ISSUE TITLE
Mobile view: enlarge images in gallery preview of entries for the wall stream

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7233]
### Is your feature request related to a problem? Please describe.

Images are too small:

![image](https://github.com/user-attachments/assets/6ec26778-6dab-4d7d-877a-69d25a977c41)

Source images:

![image](https://github.com/user-attachments/assets/8db506a0-e2bf-4391-a8dc-22ac17350de3)

![image](https://github.com/user-attachments/assets/96bb4d76-b876-48bb-9d05-eb2416a2f1e9)

### Describe the solution you'd like

Display images in 2 columns instead of 4 [here](https://github.com/humhub/humhub/blob/590238d1a2da77384a6f5bfc217aede475952735/protected/humhub/modules/file/widgets/views/showFiles.php#L33-L34) by replacing:

```php
$nonFluidColumnClass = 'col-media col-xs-3 col-sm-3 col-md-4';
$fluidColumnClass = 'col-media col-xs-3 col-sm-3 col-md-2';
```

With:

```php
$nonFluidColumnClass = 'col-media col-xs-6 col-sm-3 col-md-4';
$fluidColumnClass = 'col-media col-xs-6 col-sm-3 col-md-2';
```

Changing height in CSS from 100px to 150px by replacing:

```css
@media (max-width: 650px) {
    .post-files img {
        height: 100px;
    }
}
```

```css
@media (max-width: 650px) {
    .post-files img {
        height: 150px;
    }
}
```

Result:

![image](https://github.com/user-attachments/assets/1a163057-b301-4b96-a58d-b4e543baf53f)

### Describe alternatives you've considered

In https://github.com/humhub/humhub/blob/590238d1a2da77384a6f5bfc217aede475952735/protected/humhub/modules/file/widgets/views/showFiles.php#L33-L34, if only one image to display, display only one column (`col-xs-12`) and set height in CSS to `300px`: 

![image](https://github.com/user-attachments/assets/bdfe4606-2db9-4443-bbb2-bc53f176122b)
