### ISSUE TITLE
theme.css being overwritten

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#881]
Changes from my theme.less are being overwritten for some reason.

I have change my heading as follows

```css
  .panel-heading {
    .heading;
    font-size: 16px;
    font-weight: 300;
    background: #96b243 url(http://herbsy.cf/themes/HerbsyTheme/img/heading.jpg) no-repeat center center;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    color: white;
    border: none;
    border-bottom: 2px solid #7b953b;
    padding: 10px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
  }
```

but it renders as

```css
.panel .panel-heading {
  font-size: 16px;
  font-weight: 300;
  color: #5d6059;
  background-color: white;
  border: none;
  padding: 10px;
  border-radius: 4px;
}
```
