### ISSUE TITLE
style/theme.less split && design compiling

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#985]
I notice that the style.less, and even the theme.less files are getting a little bit large. Maybe we should think about splitting the styles up into more manageable bits? For example, lets take a look at a theoretical new style.less

``` less
//
// 1) General
// --------------------------------------------------
body {
  padding-top: 130px;
  background-color: #f4f4f4;

}

a:hover {
  text-decoration: none;
}

hr {
  margin-top: 10px;
  margin-bottom: 10px;
}

// Cols (change position property to prevent the cutting of tooltips or menus)
.col-md-1,
.col-md-2,
.col-md-3,
.col-md-4,
.col-md-5,
.col-md-6,
.col-md-7,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12 {
  position: inherit;
}

textarea {
  height: 1.5em;
}

//
// 2) Include section styles
// --------------------------------------------------

// Topbar, Nav, pagination, etc
@import "common.less"; 

// Models (Media, panels, etc)
@import "models.less"

// HumHub Components (Custom CSS)
@import "humhub.less"; 

// Yii Components
@import "yii.less"; 

// 3rd-Party Tools
@import "tools.less";

// Responsive modifications
@import "modifications.less";
```

Furthermore the "theme.less" can be expanded as well for easy navigation of sections

``` less
//
// 1) General Theme Styles
// --------------------------------------------------

//
// 2) Theme Sections
// --------------------------------------------------

// Dashboard
@import "dashboard.less";

// Spaces
@import "spaces.less";

// Profiles
@import "profiles.less";

// Directory 
@import "directory.less";
```

This allows elements which are commonly looked for to have a more common destination for users to search in when referencing style classes. And vise versa for users referencing a style they cannot find, such as being on a "profile".

---

Further, I would really love to see a option via the "Design" section to compile Less files. This can be done easily through the `exec()` command, or by using [lessphp](http://leafo.net/lessphp/)
